version: '3.8'

services:
  backend:
    build: ./fastAPI
    ports:
      - "8000:8000"

  frontend:
    build: ./my-react-app
    ports:
      - "5173:10000"
    depends_on:
      - backend